### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by netmiller** [thedevsaddam/task#3]
Any workaroud for date-formating ?

I like this tool, and I'm using it daily, but like to read more 'Europe date-formatting'. Personally I like YYYY-MM-DD HH.MM . But also other formats are more suitable; only this default (long) format is annoying .

I'm considering to fork it, and change source, but if you are willing to do some config, so it's not necessary.

Anyway, very useful tool ! 👍

**Comment by thedevsaddam** [comment]
@netmiller You can use it. Just add a credit at source code, readme.
